import Foundation

struct TarotCardData {
    static let allCards: [TarotCard] = majorArcana + cups + pentacles + swords + wands

    static let majorArcana: [TarotCard] = [
        TarotCard(id: "major-00", name: "The Fool", koreanName: "바보", suit: .major, number: 0,
                  uprightMeaning: "새로운 시작, 모험, 순수함, 자유로운 영혼",
                  reversedMeaning: "무모함, 위험 무시, 어리석은 결정",
                  imageName: "00-TheFool"),
        TarotCard(id: "major-01", name: "The Magician", koreanName: "마법사", suit: .major, number: 1,
                  uprightMeaning: "창조력, 의지력, 기술, 새로운 시작",
                  reversedMeaning: "속임수, 조작, 재능의 낭비",
                  imageName: "01-TheMagician"),
        TarotCard(id: "major-02", name: "The High Priestess", koreanName: "여사제", suit: .major, number: 2,
                  uprightMeaning: "직관, 신성한 지식, 잠재의식, 신비",
                  reversedMeaning: "비밀, 숨겨진 동기, 직관 무시",
                  imageName: "02-TheHighPriestess"),
        TarotCard(id: "major-03", name: "The Empress", koreanName: "여황제", suit: .major, number: 3,
                  uprightMeaning: "풍요, 양육, 자연, 창조성",
                  reversedMeaning: "의존, 질식, 빈곤",
                  imageName: "03-TheEmpress"),
        TarotCard(id: "major-04", name: "The Emperor", koreanName: "황제", suit: .major, number: 4,
                  uprightMeaning: "권위, 통제, 구조, 안정",
                  reversedMeaning: "독재, 융통성 없음, 과도한 통제",
                  imageName: "04-TheEmperor"),
        TarotCard(id: "major-05", name: "The Hierophant", koreanName: "교황", suit: .major, number: 5,
                  uprightMeaning: "전통, 영적 지혜, 교육, 규율",
                  reversedMeaning: "반역, 틀에 박힌 사고, 유연성 부족",
                  imageName: "05-TheHierophant"),
        TarotCard(id: "major-06", name: "The Lovers", koreanName: "연인", suit: .major, number: 6,
                  uprightMeaning: "사랑, 조화, 관계, 선택",
                  reversedMeaning: "불균형, 잘못된 선택, 갈등",
                  imageName: "06-TheLovers"),
        TarotCard(id: "major-07", name: "The Chariot", koreanName: "전차", suit: .major, number: 7,
                  uprightMeaning: "승리, 의지, 통제, 결단력",
                  reversedMeaning: "통제 상실, 방향 부족, 공격성",
                  imageName: "07-TheChariot"),
        TarotCard(id: "major-08", name: "Strength", koreanName: "힘", suit: .major, number: 8,
                  uprightMeaning: "용기, 인내, 영향력, 자제심",
                  reversedMeaning: "자제력 부족, 의심, 나약함",
                  imageName: "08-Strength"),
        TarotCard(id: "major-09", name: "The Hermit", koreanName: "은둔자", suit: .major, number: 9,
                  uprightMeaning: "내면의 탐구, 고독, 내적 지도, 성찰",
                  reversedMeaning: "고립, 외로움, 철수",
                  imageName: "09-TheHermit"),
        TarotCard(id: "major-10", name: "Wheel of Fortune", koreanName: "운명의 수레바퀴", suit: .major, number: 10,
                  uprightMeaning: "변화, 순환, 운명, 전환점",
                  reversedMeaning: "나쁜 운, 저항, 통제 불가",
                  imageName: "10-WheelOfFortune"),
        TarotCard(id: "major-11", name: "Justice", koreanName: "정의", suit: .major, number: 11,
                  uprightMeaning: "공정함, 진실, 법칙, 원인과 결과",
                  reversedMeaning: "불공정, 불균형, 책임 회피",
                  imageName: "11-Justice"),
        TarotCard(id: "major-12", name: "The Hanged Man", koreanName: "매달린 사람", suit: .major, number: 12,
                  uprightMeaning: "희생, 새로운 관점, 기다림, 항복",
                  reversedMeaning: "지연, 저항, 헛된 희생",
                  imageName: "12-TheHangedMan"),
        TarotCard(id: "major-13", name: "Death", koreanName: "죽음", suit: .major, number: 13,
                  uprightMeaning: "끝과 시작, 변화, 전환, 해방",
                  reversedMeaning: "변화에 대한 저항, 정체",
                  imageName: "13-Death"),
        TarotCard(id: "major-14", name: "Temperance", koreanName: "절제", suit: .major, number: 14,
                  uprightMeaning: "균형, 인내, 중용, 조화",
                  reversedMeaning: "불균형, 과잉, 자제력 부족",
                  imageName: "14-Temperance"),
        TarotCard(id: "major-15", name: "The Devil", koreanName: "악마", suit: .major, number: 15,
                  uprightMeaning: "속박, 집착, 유혹, 물질주의",
                  reversedMeaning: "해방, 회복, 깨달음",
                  imageName: "15-TheDevil"),
        TarotCard(id: "major-16", name: "The Tower", koreanName: "탑", suit: .major, number: 16,
                  uprightMeaning: "급격한 변화, 파괴, 계시, 각성",
                  reversedMeaning: "재난 회피, 변화에 대한 두려움",
                  imageName: "16-TheTower"),
        TarotCard(id: "major-17", name: "The Star", koreanName: "별", suit: .major, number: 17,
                  uprightMeaning: "희망, 영감, 평온, 재생",
                  reversedMeaning: "절망, 믿음 부족, 낙담",
                  imageName: "17-TheStar"),
        TarotCard(id: "major-18", name: "The Moon", koreanName: "달", suit: .major, number: 18,
                  uprightMeaning: "환상, 두려움, 불안, 잠재의식",
                  reversedMeaning: "혼란 해소, 진실 발견, 두려움 극복",
                  imageName: "18-TheMoon"),
        TarotCard(id: "major-19", name: "The Sun", koreanName: "태양", suit: .major, number: 19,
                  uprightMeaning: "기쁨, 성공, 축하, 긍정성",
                  reversedMeaning: "과도한 낙관, 우울, 지연된 성공",
                  imageName: "19-TheSun"),
        TarotCard(id: "major-20", name: "Judgement", koreanName: "심판", suit: .major, number: 20,
                  uprightMeaning: "반성, 재생, 내면의 소리, 각성",
                  reversedMeaning: "자기 의심, 내면의 비판, 후회",
                  imageName: "20-Judgement"),
        TarotCard(id: "major-21", name: "The World", koreanName: "세계", suit: .major, number: 21,
                  uprightMeaning: "완성, 성취, 여행, 통합",
                  reversedMeaning: "미완성, 지연, 목표 부재",
                  imageName: "21-TheWorld")
    ]

    static let cups: [TarotCard] = [
        TarotCard(id: "cups-01", name: "Ace of Cups", koreanName: "컵의 에이스", suit: .cups, number: 1,
                  uprightMeaning: "새로운 감정, 사랑의 시작, 직관, 영적 경험",
                  reversedMeaning: "감정의 막힘, 억압된 감정, 사랑의 거절",
                  imageName: "Cups01"),
        TarotCard(id: "cups-02", name: "Two of Cups", koreanName: "컵의 2", suit: .cups, number: 2,
                  uprightMeaning: "파트너십, 조화, 상호 매력, 균형있는 관계",
                  reversedMeaning: "불균형한 관계, 긴장, 헤어짐",
                  imageName: "Cups02"),
        TarotCard(id: "cups-03", name: "Three of Cups", koreanName: "컵의 3", suit: .cups, number: 3,
                  uprightMeaning: "축하, 우정, 공동체, 창조성",
                  reversedMeaning: "과잉, 삼각관계, 고립",
                  imageName: "Cups03"),
        TarotCard(id: "cups-04", name: "Four of Cups", koreanName: "컵의 4", suit: .cups, number: 4,
                  uprightMeaning: "명상, 무관심, 재평가, 물러남",
                  reversedMeaning: "새로운 기회, 동기 부여, 관심",
                  imageName: "Cups04"),
        TarotCard(id: "cups-05", name: "Five of Cups", koreanName: "컵의 5", suit: .cups, number: 5,
                  uprightMeaning: "상실, 후회, 실망, 비관주의",
                  reversedMeaning: "수용, 앞으로 나아감, 용서",
                  imageName: "Cups05"),
        TarotCard(id: "cups-06", name: "Six of Cups", koreanName: "컵의 6", suit: .cups, number: 6,
                  uprightMeaning: "향수, 순수함, 재회, 어린 시절",
                  reversedMeaning: "과거에 갇힘, 순진함, 현실 부정",
                  imageName: "Cups06"),
        TarotCard(id: "cups-07", name: "Seven of Cups", koreanName: "컵의 7", suit: .cups, number: 7,
                  uprightMeaning: "선택, 환상, 상상, 기회",
                  reversedMeaning: "명확성, 결단, 현실 직시",
                  imageName: "Cups07"),
        TarotCard(id: "cups-08", name: "Eight of Cups", koreanName: "컵의 8", suit: .cups, number: 8,
                  uprightMeaning: "떠남, 철회, 더 높은 목적 추구",
                  reversedMeaning: "두려움, 회피, 정체",
                  imageName: "Cups08"),
        TarotCard(id: "cups-09", name: "Nine of Cups", koreanName: "컵의 9", suit: .cups, number: 9,
                  uprightMeaning: "만족, 감정적 안정, 행복, 소원 성취",
                  reversedMeaning: "만족 지연, 불만족, 탐욕",
                  imageName: "Cups09"),
        TarotCard(id: "cups-10", name: "Ten of Cups", koreanName: "컵의 10", suit: .cups, number: 10,
                  uprightMeaning: "조화, 행복, 정렬, 가족",
                  reversedMeaning: "불화, 가치관 충돌, 긴장",
                  imageName: "Cups10"),
        TarotCard(id: "cups-11", name: "Page of Cups", koreanName: "컵의 시종", suit: .cups, number: 11,
                  uprightMeaning: "창의적 기회, 직관적 메시지, 호기심",
                  reversedMeaning: "감정적 미성숙, 환상, 불신",
                  imageName: "Cups11"),
        TarotCard(id: "cups-12", name: "Knight of Cups", koreanName: "컵의 기사", suit: .cups, number: 12,
                  uprightMeaning: "로맨스, 매력, 상상력, 이상주의",
                  reversedMeaning: "현실 도피, 변덕, 실망",
                  imageName: "Cups12"),
        TarotCard(id: "cups-13", name: "Queen of Cups", koreanName: "컵의 여왕", suit: .cups, number: 13,
                  uprightMeaning: "연민, 평온, 직관, 돌봄",
                  reversedMeaning: "의존, 불안정, 자기 돌봄 부족",
                  imageName: "Cups13"),
        TarotCard(id: "cups-14", name: "King of Cups", koreanName: "컵의 왕", suit: .cups, number: 14,
                  uprightMeaning: "감정적 균형, 통제, 관대함",
                  reversedMeaning: "조종, 변덕, 감정 억압",
                  imageName: "Cups14")
    ]

    static let pentacles: [TarotCard] = [
        TarotCard(id: "pentacles-01", name: "Ace of Pentacles", koreanName: "펜타클의 에이스", suit: .pentacles, number: 1,
                  uprightMeaning: "새로운 기회, 번영, 물질적 시작, 성장",
                  reversedMeaning: "기회 상실, 재정 불안, 연기",
                  imageName: "Pentacles01"),
        TarotCard(id: "pentacles-02", name: "Two of Pentacles", koreanName: "펜타클의 2", suit: .pentacles, number: 2,
                  uprightMeaning: "균형, 적응력, 시간 관리, 우선순위",
                  reversedMeaning: "불균형, 과부하, 혼란",
                  imageName: "Pentacles02"),
        TarotCard(id: "pentacles-03", name: "Three of Pentacles", koreanName: "펜타클의 3", suit: .pentacles, number: 3,
                  uprightMeaning: "협력, 기술, 팀워크, 학습",
                  reversedMeaning: "조화 부족, 노력 부족, 갈등",
                  imageName: "Pentacles03"),
        TarotCard(id: "pentacles-04", name: "Four of Pentacles", koreanName: "펜타클의 4", suit: .pentacles, number: 4,
                  uprightMeaning: "보존, 안전, 통제, 저축",
                  reversedMeaning: "인색함, 집착, 통제 과잉",
                  imageName: "Pentacles04"),
        TarotCard(id: "pentacles-05", name: "Five of Pentacles", koreanName: "펜타클의 5", suit: .pentacles, number: 5,
                  uprightMeaning: "재정적 어려움, 빈곤, 불안, 고립",
                  reversedMeaning: "회복, 개선, 도움 받기",
                  imageName: "Pentacles05"),
        TarotCard(id: "pentacles-06", name: "Six of Pentacles", koreanName: "펜타클의 6", suit: .pentacles, number: 6,
                  uprightMeaning: "관대함, 나눔, 자선, 균형",
                  reversedMeaning: "빚, 이기심, 불공평",
                  imageName: "Pentacles06"),
        TarotCard(id: "pentacles-07", name: "Seven of Pentacles", koreanName: "펜타클의 7", suit: .pentacles, number: 7,
                  uprightMeaning: "인내, 투자, 장기 목표, 보상",
                  reversedMeaning: "불만, 지연, 한정된 성공",
                  imageName: "Pentacles07"),
        TarotCard(id: "pentacles-08", name: "Eight of Pentacles", koreanName: "펜타클의 8", suit: .pentacles, number: 8,
                  uprightMeaning: "기술 향상, 헌신, 숙달, 세부 사항",
                  reversedMeaning: "완벽주의, 실수, 미숙함",
                  imageName: "Pentacles08"),
        TarotCard(id: "pentacles-09", name: "Nine of Pentacles", koreanName: "펜타클의 9", suit: .pentacles, number: 9,
                  uprightMeaning: "성취, 자급자족, 독립, 풍요",
                  reversedMeaning: "재정 불안, 의존, 과시",
                  imageName: "Pentacles09"),
        TarotCard(id: "pentacles-10", name: "Ten of Pentacles", koreanName: "펜타클의 10", suit: .pentacles, number: 10,
                  uprightMeaning: "유산, 안정, 부, 가족",
                  reversedMeaning: "재정 손실, 불안정, 가족 문제",
                  imageName: "Pentacles10"),
        TarotCard(id: "pentacles-11", name: "Page of Pentacles", koreanName: "펜타클의 시종", suit: .pentacles, number: 11,
                  uprightMeaning: "야망, 근면, 새로운 아이디어, 학습",
                  reversedMeaning: "계획 부족, 게으름, 비현실적 목표",
                  imageName: "Pentacles11"),
        TarotCard(id: "pentacles-12", name: "Knight of Pentacles", koreanName: "펜타클의 기사", suit: .pentacles, number: 12,
                  uprightMeaning: "책임, 신뢰성, 인내, 실용성",
                  reversedMeaning: "나태함, 무책임, 지루함",
                  imageName: "Pentacles12"),
        TarotCard(id: "pentacles-13", name: "Queen of Pentacles", koreanName: "펜타클의 여왕", suit: .pentacles, number: 13,
                  uprightMeaning: "풍요, 실용성, 양육, 안전",
                  reversedMeaning: "자기 돌봄 부족, 일 중독, 질투",
                  imageName: "Pentacles13"),
        TarotCard(id: "pentacles-14", name: "King of Pentacles", koreanName: "펜타클의 왕", suit: .pentacles, number: 14,
                  uprightMeaning: "안정, 성공, 물질적 안정, 리더십",
                  reversedMeaning: "탐욕, 물질주의, 재정 불안",
                  imageName: "Pentacles14")
    ]

    static let swords: [TarotCard] = [
        TarotCard(id: "swords-01", name: "Ace of Swords", koreanName: "소드의 에이스", suit: .swords, number: 1,
                  uprightMeaning: "돌파구, 명확성, 진실, 새로운 아이디어",
                  reversedMeaning: "혼란, 잔인함, 폭력, 불명확",
                  imageName: "Swords01"),
        TarotCard(id: "swords-02", name: "Two of Swords", koreanName: "소드의 2", suit: .swords, number: 2,
                  uprightMeaning: "결정 불가, 정체, 회피, 균형",
                  reversedMeaning: "우유부단, 혼란, 정보 과부하",
                  imageName: "Swords02"),
        TarotCard(id: "swords-03", name: "Three of Swords", koreanName: "소드의 3", suit: .swords, number: 3,
                  uprightMeaning: "가슴 아픔, 슬픔, 배신, 고통",
                  reversedMeaning: "회복, 용서, 슬픔 극복",
                  imageName: "Swords03"),
        TarotCard(id: "swords-04", name: "Four of Swords", koreanName: "소드의 4", suit: .swords, number: 4,
                  uprightMeaning: "휴식, 명상, 회복, 고요",
                  reversedMeaning: "피로, 스트레스, 소진",
                  imageName: "Swords04"),
        TarotCard(id: "swords-05", name: "Five of Swords", koreanName: "소드의 5", suit: .swords, number: 5,
                  uprightMeaning: "갈등, 패배, 불명예, 자아 중심",
                  reversedMeaning: "화해, 용서, 과거 극복",
                  imageName: "Swords05"),
        TarotCard(id: "swords-06", name: "Six of Swords", koreanName: "소드의 6", suit: .swords, number: 6,
                  uprightMeaning: "전환, 이동, 변화, 해방",
                  reversedMeaning: "저항, 과거에 갇힘, 정체",
                  imageName: "Swords06"),
        TarotCard(id: "swords-07", name: "Seven of Swords", koreanName: "소드의 7", suit: .swords, number: 7,
                  uprightMeaning: "속임수, 전략, 회피, 비밀",
                  reversedMeaning: "양심의 가책, 진실 드러남, 책임",
                  imageName: "Swords07"),
        TarotCard(id: "swords-08", name: "Eight of Swords", koreanName: "소드의 8", suit: .swords, number: 8,
                  uprightMeaning: "제한, 갇힘, 희생자 의식, 무력감",
                  reversedMeaning: "해방, 새로운 관점, 자유",
                  imageName: "Swords08"),
        TarotCard(id: "swords-09", name: "Nine of Swords", koreanName: "소드의 9", suit: .swords, number: 9,
                  uprightMeaning: "불안, 걱정, 악몽, 두려움",
                  reversedMeaning: "회복, 희망, 받아들임",
                  imageName: "Swords09"),
        TarotCard(id: "swords-10", name: "Ten of Swords", koreanName: "소드의 10", suit: .swords, number: 10,
                  uprightMeaning: "끝, 배신, 상실, 위기",
                  reversedMeaning: "회복, 재생, 새로운 시작",
                  imageName: "Swords10"),
        TarotCard(id: "swords-11", name: "Page of Swords", koreanName: "소드의 시종", suit: .swords, number: 11,
                  uprightMeaning: "호기심, 경계심, 새로운 아이디어, 에너지",
                  reversedMeaning: "험담, 교활함, 냉소",
                  imageName: "Swords11"),
        TarotCard(id: "swords-12", name: "Knight of Swords", koreanName: "소드의 기사", suit: .swords, number: 12,
                  uprightMeaning: "행동, 충동, 주장, 빠른 변화",
                  reversedMeaning: "무모함, 공격성, 성급함",
                  imageName: "Swords12"),
        TarotCard(id: "swords-13", name: "Queen of Swords", koreanName: "소드의 여왕", suit: .swords, number: 13,
                  uprightMeaning: "독립, 명확한 사고, 직접성, 지성",
                  reversedMeaning: "냉담, 잔인함, 쓴맛",
                  imageName: "Swords13"),
        TarotCard(id: "swords-14", name: "King of Swords", koreanName: "소드의 왕", suit: .swords, number: 14,
                  uprightMeaning: "권위, 진실, 지적 능력, 명확성",
                  reversedMeaning: "조종, 잔인함, 냉혹함",
                  imageName: "Swords14")
    ]

    static let wands: [TarotCard] = [
        TarotCard(id: "wands-01", name: "Ace of Wands", koreanName: "완드의 에이스", suit: .wands, number: 1,
                  uprightMeaning: "창조, 의욕, 영감, 새로운 기회",
                  reversedMeaning: "지연, 좌절, 에너지 부족",
                  imageName: "Wands01"),
        TarotCard(id: "wands-02", name: "Two of Wands", koreanName: "완드의 2", suit: .wands, number: 2,
                  uprightMeaning: "계획, 진보, 결정, 발견",
                  reversedMeaning: "두려움, 계획 부족, 우유부단",
                  imageName: "Wands02"),
        TarotCard(id: "wands-03", name: "Three of Wands", koreanName: "완드의 3", suit: .wands, number: 3,
                  uprightMeaning: "확장, 미래 계획, 전망, 기대",
                  reversedMeaning: "장애물, 좌절, 지연",
                  imageName: "Wands03"),
        TarotCard(id: "wands-04", name: "Four of Wands", koreanName: "완드의 4", suit: .wands, number: 4,
                  uprightMeaning: "축하, 조화, 기쁨, 안정",
                  reversedMeaning: "불안정, 일시적 행복, 긴장",
                  imageName: "Wands04"),
        TarotCard(id: "wands-05", name: "Five of Wands", koreanName: "완드의 5", suit: .wands, number: 5,
                  uprightMeaning: "경쟁, 갈등, 긴장, 다양성",
                  reversedMeaning: "내적 갈등, 회피, 협력",
                  imageName: "Wands05"),
        TarotCard(id: "wands-06", name: "Six of Wands", koreanName: "완드의 6", suit: .wands, number: 6,
                  uprightMeaning: "승리, 인정, 성공, 자부심",
                  reversedMeaning: "자만심, 실패, 인정 부족",
                  imageName: "Wands06"),
        TarotCard(id: "wands-07", name: "Seven of Wands", koreanName: "완드의 7", suit: .wands, number: 7,
                  uprightMeaning: "도전, 경쟁, 인내, 방어",
                  reversedMeaning: "압도됨, 포기, 굴복",
                  imageName: "Wands07"),
        TarotCard(id: "wands-08", name: "Eight of Wands", koreanName: "완드의 8", suit: .wands, number: 8,
                  uprightMeaning: "빠른 행동, 움직임, 진행, 소식",
                  reversedMeaning: "지연, 좌절, 내적 정렬",
                  imageName: "Wands08"),
        TarotCard(id: "wands-09", name: "Nine of Wands", koreanName: "완드의 9", suit: .wands, number: 9,
                  uprightMeaning: "회복력, 인내, 경계심, 마지막 노력",
                  reversedMeaning: "피로, 스트레스, 부담",
                  imageName: "Wands09"),
        TarotCard(id: "wands-10", name: "Ten of Wands", koreanName: "완드의 10", suit: .wands, number: 10,
                  uprightMeaning: "부담, 책임, 스트레스, 과부하",
                  reversedMeaning: "책임 버리기, 위임, 해방",
                  imageName: "Wands10"),
        TarotCard(id: "wands-11", name: "Page of Wands", koreanName: "완드의 시종", suit: .wands, number: 11,
                  uprightMeaning: "열정, 탐험, 발견, 자유로운 영혼",
                  reversedMeaning: "실망, 계획 부족, 성급함",
                  imageName: "Wands11"),
        TarotCard(id: "wands-12", name: "Knight of Wands", koreanName: "완드의 기사", suit: .wands, number: 12,
                  uprightMeaning: "에너지, 열정, 모험, 충동",
                  reversedMeaning: "무모함, 성급함, 좌절",
                  imageName: "Wands12"),
        TarotCard(id: "wands-13", name: "Queen of Wands", koreanName: "완드의 여왕", suit: .wands, number: 13,
                  uprightMeaning: "자신감, 독립, 결단력, 활력",
                  reversedMeaning: "이기심, 질투, 불안",
                  imageName: "Wands13"),
        TarotCard(id: "wands-14", name: "King of Wands", koreanName: "완드의 왕", suit: .wands, number: 14,
                  uprightMeaning: "리더십, 비전, 사업가 정신, 명예",
                  reversedMeaning: "독재, 무자비함, 오만함",
                  imageName: "Wands14")
    ]
}
