import Foundation

struct TarotCardData {
    static let allCards: [TarotCard] = majorArcana + cups + pentacles + swords + wands

    static let majorArcana: [TarotCard] = [
        TarotCard(id: "major-00", name: "The Fool", suit: .major, number: 0,
                  uprightMeaning: "New beginnings, adventure, innocence, free spirit",
                  reversedMeaning: "Recklessness, ignoring risks, foolish decisions",
                  imageName: "00-TheFool"),
        TarotCard(id: "major-01", name: "The Magician", suit: .major, number: 1,
                  uprightMeaning: "Creativity, willpower, skill, new beginnings",
                  reversedMeaning: "Deception, manipulation, wasted talents",
                  imageName: "01-TheMagician"),
        TarotCard(id: "major-02", name: "The High Priestess", suit: .major, number: 2,
                  uprightMeaning: "Intuition, sacred knowledge, subconscious, mystery",
                  reversedMeaning: "Secrets, hidden motives, ignoring intuition",
                  imageName: "02-TheHighPriestess"),
        TarotCard(id: "major-03", name: "The Empress", suit: .major, number: 3,
                  uprightMeaning: "Abundance, nurturing, nature, creativity",
                  reversedMeaning: "Dependence, suffocation, poverty",
                  imageName: "03-TheEmpress"),
        TarotCard(id: "major-04", name: "The Emperor", suit: .major, number: 4,
                  uprightMeaning: "Authority, control, structure, stability",
                  reversedMeaning: "Tyranny, inflexibility, excessive control",
                  imageName: "04-TheEmperor"),
        TarotCard(id: "major-05", name: "The Hierophant", suit: .major, number: 5,
                  uprightMeaning: "Tradition, spiritual wisdom, education, discipline",
                  reversedMeaning: "Rebellion, rigid thinking, lack of flexibility",
                  imageName: "05-TheHierophant"),
        TarotCard(id: "major-06", name: "The Lovers", suit: .major, number: 6,
                  uprightMeaning: "Love, harmony, relationships, choices",
                  reversedMeaning: "Imbalance, wrong choices, conflict",
                  imageName: "06-TheLovers"),
        TarotCard(id: "major-07", name: "The Chariot", suit: .major, number: 7,
                  uprightMeaning: "Victory, willpower, control, determination",
                  reversedMeaning: "Loss of control, lack of direction, aggression",
                  imageName: "07-TheChariot"),
        TarotCard(id: "major-08", name: "Strength", suit: .major, number: 8,
                  uprightMeaning: "Courage, patience, influence, self-control",
                  reversedMeaning: "Lack of self-control, doubt, weakness",
                  imageName: "08-Strength"),
        TarotCard(id: "major-09", name: "The Hermit", suit: .major, number: 9,
                  uprightMeaning: "Inner exploration, solitude, inner guidance, reflection",
                  reversedMeaning: "Isolation, loneliness, withdrawal",
                  imageName: "09-TheHermit"),
        TarotCard(id: "major-10", name: "Wheel of Fortune", suit: .major, number: 10,
                  uprightMeaning: "Change, cycles, destiny, turning point",
                  reversedMeaning: "Bad luck, resistance, lack of control",
                  imageName: "10-WheelOfFortune"),
        TarotCard(id: "major-11", name: "Justice", suit: .major, number: 11,
                  uprightMeaning: "Fairness, truth, law, cause and effect",
                  reversedMeaning: "Injustice, imbalance, avoiding responsibility",
                  imageName: "11-Justice"),
        TarotCard(id: "major-12", name: "The Hanged Man", suit: .major, number: 12,
                  uprightMeaning: "Sacrifice, new perspective, waiting, surrender",
                  reversedMeaning: "Delays, resistance, futile sacrifice",
                  imageName: "12-TheHangedMan"),
        TarotCard(id: "major-13", name: "Death", suit: .major, number: 13,
                  uprightMeaning: "Endings and beginnings, transformation, transition, release",
                  reversedMeaning: "Resistance to change, stagnation",
                  imageName: "13-Death"),
        TarotCard(id: "major-14", name: "Temperance", suit: .major, number: 14,
                  uprightMeaning: "Balance, patience, moderation, harmony",
                  reversedMeaning: "Imbalance, excess, lack of self-control",
                  imageName: "14-Temperance"),
        TarotCard(id: "major-15", name: "The Devil", suit: .major, number: 15,
                  uprightMeaning: "Bondage, obsession, temptation, materialism",
                  reversedMeaning: "Liberation, recovery, enlightenment",
                  imageName: "15-TheDevil"),
        TarotCard(id: "major-16", name: "The Tower", suit: .major, number: 16,
                  uprightMeaning: "Sudden change, destruction, revelation, awakening",
                  reversedMeaning: "Avoiding disaster, fear of change",
                  imageName: "16-TheTower"),
        TarotCard(id: "major-17", name: "The Star", suit: .major, number: 17,
                  uprightMeaning: "Hope, inspiration, serenity, renewal",
                  reversedMeaning: "Despair, lack of faith, discouragement",
                  imageName: "17-TheStar"),
        TarotCard(id: "major-18", name: "The Moon", suit: .major, number: 18,
                  uprightMeaning: "Illusion, fear, anxiety, subconscious",
                  reversedMeaning: "Clearing confusion, discovering truth, overcoming fear",
                  imageName: "18-TheMoon"),
        TarotCard(id: "major-19", name: "The Sun", suit: .major, number: 19,
                  uprightMeaning: "Joy, success, celebration, positivity",
                  reversedMeaning: "Excessive optimism, depression, delayed success",
                  imageName: "19-TheSun"),
        TarotCard(id: "major-20", name: "Judgement", suit: .major, number: 20,
                  uprightMeaning: "Reflection, rebirth, inner calling, awakening",
                  reversedMeaning: "Self-doubt, inner critic, regret",
                  imageName: "20-Judgement"),
        TarotCard(id: "major-21", name: "The World", suit: .major, number: 21,
                  uprightMeaning: "Completion, achievement, travel, integration",
                  reversedMeaning: "Incompletion, delays, lack of goals",
                  imageName: "21-TheWorld")
    ]

    static let cups: [TarotCard] = [
        TarotCard(id: "cups-01", name: "Ace of Cups", suit: .cups, number: 1,
                  uprightMeaning: "New feelings, beginning of love, intuition, spiritual experience",
                  reversedMeaning: "Blocked emotions, repressed feelings, rejection of love",
                  imageName: "Cups01"),
        TarotCard(id: "cups-02", name: "Two of Cups", suit: .cups, number: 2,
                  uprightMeaning: "Partnership, harmony, mutual attraction, balanced relationship",
                  reversedMeaning: "Imbalanced relationship, tension, separation",
                  imageName: "Cups02"),
        TarotCard(id: "cups-03", name: "Three of Cups", suit: .cups, number: 3,
                  uprightMeaning: "Celebration, friendship, community, creativity",
                  reversedMeaning: "Excess, love triangle, isolation",
                  imageName: "Cups03"),
        TarotCard(id: "cups-04", name: "Four of Cups", suit: .cups, number: 4,
                  uprightMeaning: "Meditation, apathy, reevaluation, withdrawal",
                  reversedMeaning: "New opportunities, motivation, interest",
                  imageName: "Cups04"),
        TarotCard(id: "cups-05", name: "Five of Cups", suit: .cups, number: 5,
                  uprightMeaning: "Loss, regret, disappointment, pessimism",
                  reversedMeaning: "Acceptance, moving forward, forgiveness",
                  imageName: "Cups05"),
        TarotCard(id: "cups-06", name: "Six of Cups", suit: .cups, number: 6,
                  uprightMeaning: "Nostalgia, innocence, reunion, childhood",
                  reversedMeaning: "Stuck in the past, naivety, denying reality",
                  imageName: "Cups06"),
        TarotCard(id: "cups-07", name: "Seven of Cups", suit: .cups, number: 7,
                  uprightMeaning: "Choices, illusion, imagination, opportunities",
                  reversedMeaning: "Clarity, decision, facing reality",
                  imageName: "Cups07"),
        TarotCard(id: "cups-08", name: "Eight of Cups", suit: .cups, number: 8,
                  uprightMeaning: "Departure, withdrawal, seeking higher purpose",
                  reversedMeaning: "Fear, avoidance, stagnation",
                  imageName: "Cups08"),
        TarotCard(id: "cups-09", name: "Nine of Cups", suit: .cups, number: 9,
                  uprightMeaning: "Contentment, emotional stability, happiness, wish fulfillment",
                  reversedMeaning: "Delayed satisfaction, dissatisfaction, greed",
                  imageName: "Cups09"),
        TarotCard(id: "cups-10", name: "Ten of Cups", suit: .cups, number: 10,
                  uprightMeaning: "Harmony, happiness, alignment, family",
                  reversedMeaning: "Discord, conflicting values, tension",
                  imageName: "Cups10"),
        TarotCard(id: "cups-11", name: "Page of Cups", suit: .cups, number: 11,
                  uprightMeaning: "Creative opportunity, intuitive messages, curiosity",
                  reversedMeaning: "Emotional immaturity, illusion, distrust",
                  imageName: "Cups11"),
        TarotCard(id: "cups-12", name: "Knight of Cups", suit: .cups, number: 12,
                  uprightMeaning: "Romance, charm, imagination, idealism",
                  reversedMeaning: "Escapism, moodiness, disappointment",
                  imageName: "Cups12"),
        TarotCard(id: "cups-13", name: "Queen of Cups", suit: .cups, number: 13,
                  uprightMeaning: "Compassion, serenity, intuition, caring",
                  reversedMeaning: "Dependency, instability, lack of self-care",
                  imageName: "Cups13"),
        TarotCard(id: "cups-14", name: "King of Cups", suit: .cups, number: 14,
                  uprightMeaning: "Emotional balance, control, generosity",
                  reversedMeaning: "Manipulation, moodiness, emotional repression",
                  imageName: "Cups14")
    ]

    static let pentacles: [TarotCard] = [
        TarotCard(id: "pentacles-01", name: "Ace of Pentacles", suit: .pentacles, number: 1,
                  uprightMeaning: "New opportunity, prosperity, material beginning, growth",
                  reversedMeaning: "Lost opportunity, financial insecurity, postponement",
                  imageName: "Pentacles01"),
        TarotCard(id: "pentacles-02", name: "Two of Pentacles", suit: .pentacles, number: 2,
                  uprightMeaning: "Balance, adaptability, time management, priorities",
                  reversedMeaning: "Imbalance, overload, chaos",
                  imageName: "Pentacles02"),
        TarotCard(id: "pentacles-03", name: "Three of Pentacles", suit: .pentacles, number: 3,
                  uprightMeaning: "Collaboration, skill, teamwork, learning",
                  reversedMeaning: "Lack of harmony, lack of effort, conflict",
                  imageName: "Pentacles03"),
        TarotCard(id: "pentacles-04", name: "Four of Pentacles", suit: .pentacles, number: 4,
                  uprightMeaning: "Conservation, security, control, saving",
                  reversedMeaning: "Greed, obsession, excessive control",
                  imageName: "Pentacles04"),
        TarotCard(id: "pentacles-05", name: "Five of Pentacles", suit: .pentacles, number: 5,
                  uprightMeaning: "Financial hardship, poverty, insecurity, isolation",
                  reversedMeaning: "Recovery, improvement, receiving help",
                  imageName: "Pentacles05"),
        TarotCard(id: "pentacles-06", name: "Six of Pentacles", suit: .pentacles, number: 6,
                  uprightMeaning: "Generosity, sharing, charity, balance",
                  reversedMeaning: "Debt, selfishness, unfairness",
                  imageName: "Pentacles06"),
        TarotCard(id: "pentacles-07", name: "Seven of Pentacles", suit: .pentacles, number: 7,
                  uprightMeaning: "Patience, investment, long-term goals, reward",
                  reversedMeaning: "Frustration, delays, limited success",
                  imageName: "Pentacles07"),
        TarotCard(id: "pentacles-08", name: "Eight of Pentacles", suit: .pentacles, number: 8,
                  uprightMeaning: "Skill development, dedication, mastery, attention to detail",
                  reversedMeaning: "Perfectionism, mistakes, lack of skill",
                  imageName: "Pentacles08"),
        TarotCard(id: "pentacles-09", name: "Nine of Pentacles", suit: .pentacles, number: 9,
                  uprightMeaning: "Achievement, self-sufficiency, independence, abundance",
                  reversedMeaning: "Financial insecurity, dependence, showing off",
                  imageName: "Pentacles09"),
        TarotCard(id: "pentacles-10", name: "Ten of Pentacles", suit: .pentacles, number: 10,
                  uprightMeaning: "Legacy, stability, wealth, family",
                  reversedMeaning: "Financial loss, instability, family issues",
                  imageName: "Pentacles10"),
        TarotCard(id: "pentacles-11", name: "Page of Pentacles", suit: .pentacles, number: 11,
                  uprightMeaning: "Ambition, diligence, new ideas, learning",
                  reversedMeaning: "Lack of planning, laziness, unrealistic goals",
                  imageName: "Pentacles11"),
        TarotCard(id: "pentacles-12", name: "Knight of Pentacles", suit: .pentacles, number: 12,
                  uprightMeaning: "Responsibility, reliability, patience, practicality",
                  reversedMeaning: "Laziness, irresponsibility, boredom",
                  imageName: "Pentacles12"),
        TarotCard(id: "pentacles-13", name: "Queen of Pentacles", suit: .pentacles, number: 13,
                  uprightMeaning: "Abundance, practicality, nurturing, security",
                  reversedMeaning: "Lack of self-care, workaholism, jealousy",
                  imageName: "Pentacles13"),
        TarotCard(id: "pentacles-14", name: "King of Pentacles", suit: .pentacles, number: 14,
                  uprightMeaning: "Stability, success, material security, leadership",
                  reversedMeaning: "Greed, materialism, financial insecurity",
                  imageName: "Pentacles14")
    ]

    static let swords: [TarotCard] = [
        TarotCard(id: "swords-01", name: "Ace of Swords", suit: .swords, number: 1,
                  uprightMeaning: "Breakthrough, clarity, truth, new ideas",
                  reversedMeaning: "Confusion, cruelty, violence, lack of clarity",
                  imageName: "Swords01"),
        TarotCard(id: "swords-02", name: "Two of Swords", suit: .swords, number: 2,
                  uprightMeaning: "Difficult decisions, stalemate, avoidance, balance",
                  reversedMeaning: "Indecision, confusion, information overload",
                  imageName: "Swords02"),
        TarotCard(id: "swords-03", name: "Three of Swords", suit: .swords, number: 3,
                  uprightMeaning: "Heartbreak, sorrow, betrayal, pain",
                  reversedMeaning: "Recovery, forgiveness, overcoming grief",
                  imageName: "Swords03"),
        TarotCard(id: "swords-04", name: "Four of Swords", suit: .swords, number: 4,
                  uprightMeaning: "Rest, meditation, recovery, stillness",
                  reversedMeaning: "Exhaustion, stress, burnout",
                  imageName: "Swords04"),
        TarotCard(id: "swords-05", name: "Five of Swords", suit: .swords, number: 5,
                  uprightMeaning: "Conflict, defeat, dishonor, self-interest",
                  reversedMeaning: "Reconciliation, forgiveness, overcoming the past",
                  imageName: "Swords05"),
        TarotCard(id: "swords-06", name: "Six of Swords", suit: .swords, number: 6,
                  uprightMeaning: "Transition, moving on, change, release",
                  reversedMeaning: "Resistance, stuck in the past, stagnation",
                  imageName: "Swords06"),
        TarotCard(id: "swords-07", name: "Seven of Swords", suit: .swords, number: 7,
                  uprightMeaning: "Deception, strategy, evasion, secrets",
                  reversedMeaning: "Guilty conscience, truth revealed, taking responsibility",
                  imageName: "Swords07"),
        TarotCard(id: "swords-08", name: "Eight of Swords", suit: .swords, number: 8,
                  uprightMeaning: "Restriction, trapped, victim mentality, powerlessness",
                  reversedMeaning: "Liberation, new perspective, freedom",
                  imageName: "Swords08"),
        TarotCard(id: "swords-09", name: "Nine of Swords", suit: .swords, number: 9,
                  uprightMeaning: "Anxiety, worry, nightmares, fear",
                  reversedMeaning: "Recovery, hope, acceptance",
                  imageName: "Swords09"),
        TarotCard(id: "swords-10", name: "Ten of Swords", suit: .swords, number: 10,
                  uprightMeaning: "Endings, betrayal, loss, crisis",
                  reversedMeaning: "Recovery, regeneration, new beginnings",
                  imageName: "Swords10"),
        TarotCard(id: "swords-11", name: "Page of Swords", suit: .swords, number: 11,
                  uprightMeaning: "Curiosity, vigilance, new ideas, energy",
                  reversedMeaning: "Gossip, cunning, cynicism",
                  imageName: "Swords11"),
        TarotCard(id: "swords-12", name: "Knight of Swords", suit: .swords, number: 12,
                  uprightMeaning: "Action, impulsiveness, assertion, rapid change",
                  reversedMeaning: "Recklessness, aggression, haste",
                  imageName: "Swords12"),
        TarotCard(id: "swords-13", name: "Queen of Swords", suit: .swords, number: 13,
                  uprightMeaning: "Independence, clear thinking, directness, intelligence",
                  reversedMeaning: "Coldness, cruelty, bitterness",
                  imageName: "Swords13"),
        TarotCard(id: "swords-14", name: "King of Swords", suit: .swords, number: 14,
                  uprightMeaning: "Authority, truth, intellectual power, clarity",
                  reversedMeaning: "Manipulation, cruelty, ruthlessness",
                  imageName: "Swords14")
    ]

    static let wands: [TarotCard] = [
        TarotCard(id: "wands-01", name: "Ace of Wands", suit: .wands, number: 1,
                  uprightMeaning: "Creation, enthusiasm, inspiration, new opportunity",
                  reversedMeaning: "Delays, frustration, lack of energy",
                  imageName: "Wands01"),
        TarotCard(id: "wands-02", name: "Two of Wands", suit: .wands, number: 2,
                  uprightMeaning: "Planning, progress, decisions, discovery",
                  reversedMeaning: "Fear, lack of planning, indecision",
                  imageName: "Wands02"),
        TarotCard(id: "wands-03", name: "Three of Wands", suit: .wands, number: 3,
                  uprightMeaning: "Expansion, future planning, foresight, anticipation",
                  reversedMeaning: "Obstacles, frustration, delays",
                  imageName: "Wands03"),
        TarotCard(id: "wands-04", name: "Four of Wands", suit: .wands, number: 4,
                  uprightMeaning: "Celebration, harmony, joy, stability",
                  reversedMeaning: "Instability, temporary happiness, tension",
                  imageName: "Wands04"),
        TarotCard(id: "wands-05", name: "Five of Wands", suit: .wands, number: 5,
                  uprightMeaning: "Competition, conflict, tension, diversity",
                  reversedMeaning: "Inner conflict, avoidance, cooperation",
                  imageName: "Wands05"),
        TarotCard(id: "wands-06", name: "Six of Wands", suit: .wands, number: 6,
                  uprightMeaning: "Victory, recognition, success, pride",
                  reversedMeaning: "Arrogance, failure, lack of recognition",
                  imageName: "Wands06"),
        TarotCard(id: "wands-07", name: "Seven of Wands", suit: .wands, number: 7,
                  uprightMeaning: "Challenge, competition, perseverance, defense",
                  reversedMeaning: "Overwhelmed, giving up, surrender",
                  imageName: "Wands07"),
        TarotCard(id: "wands-08", name: "Eight of Wands", suit: .wands, number: 8,
                  uprightMeaning: "Rapid action, movement, progress, news",
                  reversedMeaning: "Delays, frustration, internal alignment",
                  imageName: "Wands08"),
        TarotCard(id: "wands-09", name: "Nine of Wands", suit: .wands, number: 9,
                  uprightMeaning: "Resilience, perseverance, vigilance, last push",
                  reversedMeaning: "Exhaustion, stress, burden",
                  imageName: "Wands09"),
        TarotCard(id: "wands-10", name: "Ten of Wands", suit: .wands, number: 10,
                  uprightMeaning: "Burden, responsibility, stress, overload",
                  reversedMeaning: "Releasing burdens, delegation, liberation",
                  imageName: "Wands10"),
        TarotCard(id: "wands-11", name: "Page of Wands", suit: .wands, number: 11,
                  uprightMeaning: "Enthusiasm, exploration, discovery, free spirit",
                  reversedMeaning: "Disappointment, lack of planning, haste",
                  imageName: "Wands11"),
        TarotCard(id: "wands-12", name: "Knight of Wands", suit: .wands, number: 12,
                  uprightMeaning: "Energy, passion, adventure, impulsiveness",
                  reversedMeaning: "Recklessness, haste, frustration",
                  imageName: "Wands12"),
        TarotCard(id: "wands-13", name: "Queen of Wands", suit: .wands, number: 13,
                  uprightMeaning: "Confidence, independence, determination, vitality",
                  reversedMeaning: "Selfishness, jealousy, insecurity",
                  imageName: "Wands13"),
        TarotCard(id: "wands-14", name: "King of Wands", suit: .wands, number: 14,
                  uprightMeaning: "Leadership, vision, entrepreneurship, honor",
                  reversedMeaning: "Tyranny, ruthlessness, arrogance",
                  imageName: "Wands14")
    ]
}
